### ISSUE TITLE
National parks rendered incorrectly

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#586] opened 2015-03-04 16:53 UTC
I suspect that this bug is in the map writer, but it could also be caused by the rendering code. Large polygons, such as national parks are rendered as large transparent areas with some green on the edges. Sometimes, the polygon fragments are inverted - they are filled in when they should be cut out instead. 
![mapsforgebug](https://cloud.githubusercontent.com/assets/1422186/6488366/de1413c4-c24b-11e4-8e72-bd843582a65e.jpg)
See the attached JPG. The left pane is rendered with mapsforge, and the right pane is a screen grab from openstreetmaps.org.

**Comment by devemux86** [comment] 2015-03-04 20:50
I can confirm the behavior at that area too.

**Comment by applantation** [comment] 2015-03-04 20:52
Is that area a relation or a single long way? Is the osm data actually
valid?
Am 04.03.2015 17:50 schrieb "Emux" <notifications@github.com>:

**Comment by devemux86** [comment] 2015-03-04 21:03
I have not checked the osm data.
But playing around I see that actually the whole map has these issues.

@lincomatic 
Have you seen the same issues with [OpenAndroMaps](http://www.openandromaps.org/en/) map?

**Comment by lincomatic** [comment] 2015-03-04 22:21
The OSM data should be valid since openstreetmaps.org displays it OK, as I showed in my JPG, but I don't know if maybe the error is caused by some other tool in your toolchain

**Comment by lincomatic** [comment] 2015-03-04 22:25
I'm not familiar with OpenAndroMaps. Are they compatible with Mapsforge?
> @lincomatic 
> Have you seen the same issues with OpenAndroMaps map?
>

**Comment by lincomatic** [comment] 2015-03-05 03:26
OK, I just tried it using OruxMaps to display OpenAndroMaps of California, and it renders correctly
![screenshot_2015-03-04-19-17-43](https://cloud.githubusercontent.com/assets/1422186/6498744/5f0910f8-c2a4-11e4-8ca5-ac7926a0ecb6.png)

**Comment by lincomatic** [comment] 2015-03-05 03:40
OK, I was wrong.. the problem is the map file. I tried the map from download.mapsforge.org on OruxMaps and it also shows the bug. And attached below is the OpenAndroMaps map displayed with SwingMapViewer, and it looks good. What tool does OpenAndroMaps use to create the maps? Don't they use osmosis and the mapsforge writer plugin?
![image1](https://cloud.githubusercontent.com/assets/1422186/6498863/3c008fe4-c2a6-11e4-88ef-5cae9e2395c6.jpg)

**Comment by devemux86** [comment] 2015-03-05 07:28
OpenAndroMaps build maps with Mapsforge (and Osmosis).
They both use as source the OSM data set.
But OpenAndroMaps use their own tag-mapping / TagTransform for parsing the osm data.

**Comment by devemux86** [comment] 2015-03-05 07:30
I just downloaded OpenAndroMaps California and it shows at info "mapsforge-map-writer-0.5.0".

**Comment by lincomatic** [comment] 2015-03-05 21:12
Interesting, because yesterday, I used both 0.5.0 and 0.5.1-rc4 versions of map-writer with the latest osmosis (0.43.1), and both maps I generated had the polygon bug. The original data I used to find the bug was downloaded from download.mapsforge.org. Any idea what could be different about OpenAndroMaps could be doing differently? I don't think tag mapping transforms could affect polygons, correct?

**Comment by devemux86** [comment] 2015-03-05 21:19
Christian (OpenAndroMaps) can answer better for his work (you could ask in its forum too).

But tag-mapping can play significant role, e.g. maybe ```force-polygon-line``` is used here for different results.

**Comment by devemux86** [comment] 2015-03-05 21:28
The above tag definifiton can be seen at tag-mapping schema [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/resources/tag-mapping.xsd#L117-L125).

**Comment by lincomatic** [comment] 2015-03-06 00:12
Wow, you were right. The bug is in the default tag-mapping.xml. National parks are polygons, not lines, so changing
		<osm-tag key="boundary" value="national_park" force-polygon-line="true" zoom-appear="12" />

to
		<osm-tag key="boundary" value="national_park" force-polygon-line="false" zoom-appear="12" />

makes them render properly.

**Comment by lincomatic** [comment] 2015-03-06 00:13
Wow, you were right! the bug was in the default tag-mapping.xml. National parks are polygons, not admin boundaries, so changing

		<osm-tag key="boundary" value="national_park" force-polygon-line="true" zoom-appear="12" />

to 

		<osm-tag key="boundary" value="national_park" force-polygon-line="false" zoom-appear="12" />

makes them render properly.

**Comment by devemux86** [comment] 2015-03-06 07:08
We should be careful with the changes at the default tag-mapping, since it's used for producing the maps in the whole world.
Ludwig what's your thoughts about that?

**Comment by lincomatic** [comment] 2015-03-06 21:38
Some more data... OpenAndroMaps has force-polygon-line turned off in their default mapping file. I opened up a bunch of their maps around the world and they look OK. But I don't know if they use that setting in all of their maps or not. I did find a few more maps with errors, and they looked better in OpenAndroMaps. But I understand your reluctance to change it w/o more testing.

**Comment by eartrumpet** [comment] 2015-04-05 21:04
Just found this issue - yes, in OpenAndroMaps force-polygon-line was turned off because of this issue and hast been for some time without negative side effects. I think it was active in the default tag-mapping because it's a boundary tag and it makes sense for administrative boundaries, but not with national_park and similar.

**Comment by devemux86** [comment] 2015-04-06 07:22
Ok so we could remove ```force-polygon-line``` at tag-mapping.xml [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/config/tag-mapping.xml#L429) for when ```boundary``` is ```national_park``` ?

The only other case where is used is at administrative boundaries.

**Comment by devemux86** [comment] 2015-04-06 20:04
With 13bb0d7fbb982f401f769639116b1376490fed54 I pushed a fix on dev, removing the ```force-polygon-line``` when ```boundary``` is ```national_park```.

Ludwig can integrate it later in our build server.

**Comment by ludwigb** [comment] 2015-04-07 11:09
Thanks for sorting this out, I will integrate this a bit later and start
regenerating the map.

**Comment by applantation** [comment] 2015-04-07 11:36
Done, build new writer based on dev, installed it and restarted the
process. This will, as usual, take quite a while.

Ludwig

**Comment by devemux86** [comment] 2015-04-25 06:34
I see in our latest map the problem seems solved with the above change in tag-mapping, so I'm closing this.

If there are more map issues please use the MapCreator issues list:
https://github.com/mapsforge/mapsforge-mapcreator/issues

**Closed by devemux86** 2015-04-25 06:34 UTC
