### ISSUE TITLE
Invalid Longitude -180.00000000000003 near international date line

### ISSUE THREAD

**Issue by lincomatic** [mapsforge/mapsforge#643] opened 2015-07-05 22:31 UTC
I recently built a world map and found a problem opening block z=12,x=0,y=882:

WARNING: invalid number of way nodes: 0
Exception in thread "main" java.lang.IllegalArgumentException: invalid longitude
: -180.00000000000003
        at org.mapsforge.core.util.LatLongUtils.validateLongitude(LatLongUtils.j
ava:185)
        at org.mapsforge.core.model.BoundingBox.<init>(BoundingBox.java:78)
        at org.mapsforge.core.model.BoundingBox.intersectsArea(BoundingBox.java:
226)
        at org.mapsforge.map.reader.MapFile.processWays(MapFile.java:833)
        at org.mapsforge.map.reader.MapFile.processBlock(MapFile.java:498)
        at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:591)
        at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:346)
        at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(Database
Renderer.java:183)
        at org.mapsforge.map.layer.renderer.TileRendererLayer.renderAndSaveTiles
(TileRendererLayer.java:194)
        at org.mapsforge.map.swing.MapViewer.addLayers(MapViewer.java:125)
        at org.mapsforge.map.swing.MapViewer.main(MapViewer.java:87)

The error message is getting tripped up by roundoff error. I think we need to loosen up the boundary a bit.

**Comment by devemux86** [comment] 2015-07-06 06:48
The ```world.map``` in our server (I describe the process [here](https://groups.google.com/forum/#!topic/mapsforge-dev/1PzOYvFs8sE)) does not have that behavior.

So is something special with your implementation, e.g. what's the ```bbox```?

**Comment by applantation** [comment] 2015-07-06 09:26
I think the problem is that it is possible to encode a point on or near the
dateline in the map file in a way that is technically correct, but when
decoded again will result in an invalid longitude. IIRC this has been
observed before in some other fashion.
(This could even just be -180 or 180 itself, not tried, but likely).

**Comment by lincomatic** [comment] 2015-07-06 18:02
My map is a full resolution map using the same procedure as the mapsforge-mapcreator. The difference is just that I build the pieces of the map in small chunks and then stitch them together using a C++ program that I wrote to build the world map. The C++ program does not modify any of the coordinates. It only copies the binary data.

**Comment by devemux86** [comment] 2016-03-13 18:15
@lincomatic I pushed a fix related to #780.
Can you check again your world map?

**Comment by lincomatic** [comment] 2016-03-16 03:41
Yes, this will work. I fixed it a slightly different way. Since we are trying to just account for roundoff error, I used the following code instead:

            if ((wayNodeLongitude < LatLongUtils.LONGITUDE_MIN) &&
	        ((LatLongUtils.LONGITUDE_MIN - wayNodeLongitude) < 0.001)) {
                wayNodeLongitude = LatLongUtils.LONGITUDE_MIN;
            } else if ((wayNodeLongitude > LatLongUtils.LONGITUDE_MAX) &&
                ((wayNodeLongitude - LatLongUtils.LONGITUDE_MAX) < 0.001)) {
                wayNodeLongitude = LatLongUtils.LONGITUDE_MAX;
            }


This way, we correct for the roundoff errors, but still let validateLongitude() catch corrupted values that are clearly bad.

**Comment by devemux86** [comment] 2016-03-16 08:08
Considering that map build is correct, at map file decoding should we expect any invalid coordinates?

Also why the choice of 3 decimals?

**Comment by lincomatic** [comment] 2016-03-16 08:09
We shouldn't expect invalid coordinates. It's to catch bugs or corrupted data. The 3 decimals choice was rather arbitrary.

**Comment by devemux86** [comment] 2016-03-16 08:38
I pushed your improvement, thanks!

**Closed by devemux86** 2016-03-16 08:38 UTC
Labels: bug

**Comment by ludwigb** [comment] 2016-03-16 13:57
+1
