### ISSUE TITLE
dy for way elements should scale with zoom levels

### ISSUE THREAD

**Issue by eartrumpet** [mapsforge/mapsforge#580] opened 2015-02-05 09:34 UTC
I played a bit with dy for lines/pathText/lineSymbol with mapsforge 0.5.

I find it quite hard to use in many cases, as dy doesn't scale with zoom as line width does.

For example if I want to make a tunnel with two parallel lines and dy, it's about the right size with this code at ZL16:

    <rule e="way" k="tunnel" v="yes">
        <rule e="way" k="highway" v="motorway">
            <line stroke="#80CCCCCC" dy="4" stroke-width="0.5" stroke-dasharray="10,2" stroke-linecap="butt" />
            <line stroke="#80CCCCCC" dy="-4" stroke-width="0.5" stroke-dasharray="10,2" stroke-linecap="butt" />
        </rule>
    </rule>
    <rule e="way" k="tunnel" v="~">
        <rule e="way" k="highway" v="motorway">
            <line stroke="#FF7700" stroke-width="2.5" stroke-linecap="butt" />
            <line stroke="#FFFF00" stroke-width="0.8" />
        </rule>
    </rule>

But the tunnel lines move farther away with lower zoom, and closer together with higher zoom. So I have to make lots of different rules for different ZL if I want to make it work.
Same goes for pathText: at one ZL it is within a close distance to the corresponding line, at another it has a far distance, at a third it's above the line (same goes for lineSymbol).

So at the moment it's nice to have, but a bit cumbersome to use. 

It would make much more sense if dy for way elements would scale with zoom level the same as line width scales.

**Comment by ludwigb** [comment] 2015-02-07 21:58
Let me know if this works, so this issue can be closed.

**Comment by eartrumpet** [comment] 2015-02-08 08:42
Thanks for the quick fix, works great for me.

**Comment by eartrumpet** [comment] 2015-02-08 08:54
Sorry, previous test was only for line with dy. I retested with pathText and lineSymbol, this still doesn't scale in sync with lines.

**Comment by ludwigb** [comment] 2015-02-08 11:52
Thanks for checking. 

Just pushed fix to dev that addresses PathText (where the scaling operation was applied in the wrong place) and LineSymbol (which I had forgotten entirely). 
Note to self: never assume that similar code will just work without testing.

**Comment by eartrumpet** [comment] 2015-02-09 20:33
Thanks for the second fix. It's getting close, but not quite: pathText and lineSymbol work mostly as expected, but the distance is moving a bit with zooming, so at some point the symbol/text is touching the highway, sometimes not with this test code:

		<rule e="way" k="highway" v="secondary|tertiary|primary|residential|motorway">
			<line stroke="#000000" stroke-width="3" stroke-linecap="butt" />
			<line stroke="#FFFFFF" stroke-width="2.8" stroke-linecap="butt" />
			<pathText k="ref" font-style="bold" dy="2" font-size="10" stroke="#215E8F" fill="#FFFFFF" stroke-width="1.2" />
			<pathText k="name" font-style="bold" dy="-2" font-size="10" stroke="#215E8F" fill="#FFFFFF" stroke-width="1.2" />
			<lineSymbol src="assets:symbols/peak1.svg" dy="1" repeat="true" />
		</rule>

**Comment by devemux86** [comment] 2015-02-09 21:15
Tobias on what device are you making the tests (to check the device dpi) and at what zoom levels there are still issues?

Also note that the stroke width is scaled for zoom levels >12 as seen [here](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/renderer/DatabaseRenderer.java#L447-L456) with a base [1.5](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/renderer/DatabaseRenderer.java#L75)

**Comment by ludwigb** [comment] 2015-02-09 22:30
I have not retested this yet, but I can imagine what the problem is: technically when scaling with zoom level the real coordinates shift a bit, e.g. a road that gets wider and if there was a road parallel to it at one point these two roads would overlap even though in reality they do not overlap. Same with pathText and lineSymbol, particularly as the text and the symbol center runs lies on the middle of the dy-line. So, I am not sure on how to avoid this entirely. 

Best to send in some screenshots to really illustrate the issue.

**Comment by eartrumpet** [comment] 2015-02-10 12:14
I'm using Genymotion Emulator, at the moment at 240dpi. Here are some examples with the test code from above:
lineSymbol: at 11 it's pretty far away from the lines, at 15 it's close, at 21 it's inside the lines.
![linesymbol](https://cloud.githubusercontent.com/assets/10862696/6126958/18c43e90-b126-11e4-90c8-e3adf74804f1.png)

pathText: at 10 it is above both lines, at 15 it's above the lower line borders, at 19 it's outside the lines.
![pathtext](https://cloud.githubusercontent.com/assets/10862696/6126959/18c80a3e-b126-11e4-9772-2afc289bc09b.png)

What I had in mind was: the relative distance to the way is always the same. So if the stroke width is scale for ZL>12 with a base of 1.5, dy should also be scaled for that.

**Comment by devemux86** [comment] 2015-02-14 17:28
Searching it, I think for dy we don't need a multiplier for scaling, but an addition of the difference between the new stroke width and the old one.

The thing is that inside e.g. the lineSymbol / pathText rules we don't know the stroke width of the related line.

**Comment by devemux86** [comment] 2015-02-14 19:17
Tobias in your last example if you want e.g. the line symbol to touch the line then you need to set its ```dy``` to a value half of the outer line stroke width, in this case:
```xml
<lineSymbol src="file:symbols/peak.png" dy="1.5" repeat="true" />
```

And use a symbol that does not have canvas larger than the image itself, like the ```"peak.png"```.

I followed these rules and the symbol was all the time touching the line in all zoom levels.

**Comment by eartrumpet** [comment] 2015-02-17 21:11
Hi Emux,
thanks for your replies.
lineSymbol works now, you're right. It's just the canvas (and the not zooming symbol) that makes it look like it's still moving.

The problem with pathText is maybe that the dy reference line of the caption isn't the top nor the ground line of the letters.
It would make sense to use as the dy reference line the top line of the caption for positive dy values, and the bottom line for negative dy values.

**Comment by devemux86** [comment] 2015-04-19 13:43
I suppose we can close this.

**Closed by devemux86** 2015-04-19 13:43 UTC
Labels: enhancement
