### ISSUE TITLE
Map is sometimes distorted

### ISSUE THREAD

**Issue by NamtarR** [mapsforge/mapsforge#770] opened 2016-01-13 08:57 UTC
Hello! I am using mapsforge library in my two working projects. Map workflow is based on code examples and everything seemed to work just fine. After some time I noticed that map becomes distorted after touch events. It happens really rarely and on rare devices but still it does. It seems that such an issue does not appear on kitkat+ devices. Here is a screenshot of my test 4.1 device where I could achieve such a strange behavior. 
![Screenshot]
(https://trello-attachments.s3.amazonaws.com/56960871861c202ff988e7a4/480x800/aae104027430a470a882c9f1d724f466/Screenshot_2016-01-05-16-37-53.png)

**Comment by devemux86** [comment] 2016-01-13 09:00
Have you [hardware acceleration](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#hardware-acceleration) enabled on application or view level?
What device is that?

(Closing as duplicate of  #440)

**Closed by devemux86** 2016-01-13 09:00 UTC
