### ISSUE TITLE
Labels for underground rivers are shown on map

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#589] opened 2015-03-13 20:18 UTC
I do not know if this is map writer or map renderer issue, but map contains labels for underground rivers. You can find an example at 55.818406 37.651917 - horizontal blue labels to the left and vertical blue labels to the bottom starting at zoom 17, the same labels to the right above children's playground to the right at zoom 19. It can be viewed on moskovskaya.map (Russia).

**Comment by devemux86** [comment] 2015-03-13 20:42
Can you provide a screenshot ?
I probably can reproduce it with RenderThemeV4 but not with Osmarender.

The map rendering places the symbols and labels above all other elements, i.e. you cannot use polygons as masks.
Though you can play with the render theme rules in order to show/hide the elements per zoom level.

**Comment by ludwigb** [comment] 2015-03-13 23:33
I think there is no such concept as that things underground will not
receive labels. I think this is just a limitation of our current process.

**Comment by andreynovikov** [comment] 2015-03-15 08:07
Here is the screenshot:
![screenshot_2015-03-14-00-16-55](https://cloud.githubusercontent.com/assets/2943625/6655174/2e4e991c-cb03-11e4-85ef-7ee5d2ff8125.png)

These are two underground rivers, one of them (vertical) is joining the other (horizontal) in the center of the view.

**Comment by ludwigb** [comment] 2015-03-15 15:02
I think what happens there is that simply the river is not shown because it
is underground (i.e. layers on top of it, the park, roads etc).

I think it should be possible to filter out the names by adding another
rule to the rendertheme that would only display rivers where the layer
attribute is not set. (Unfortunately, the syntax is tricky here as we do
only match on strings, so saying 'anything lower than 0' is not possible).

(I personally think that issues like that are a strong argument for an SQL
based map file format, as it would be much easier to filter out rivers on
such conditions).

Ludwig

**Comment by devemux86** [comment] 2015-03-15 15:10
I think it should not only be based on ```layer``` attribute (which is not always present).

There should be possible the polygons to mask entirely the below elements, regardless if they are other polygons (work now) or symbols / labels (not work now).

**Comment by applantation** [comment] 2015-03-15 15:31
I do not think masking with polygons is the right idea: that would mean in
this case that the river would not show if something else is rendered on
top, but would show if nothing had been drawn on top of it. But it is still
the same underground river.

It is a bit like a tunnel situation: a tunnel is rendered differently from
other roads, but it is still rendered (as not rendering it would say 'there
is no road'.)

I think equally in this case the underground river should be either
rendered in some sort of different way (together with label) or not at all
(then also without label).

At this point I do not have a great solution to this.

**Comment by devemux86** [comment] 2015-03-15 15:38
I was meaning as an option.
I had the case of building marine maps from ENC data (which use masks).
It was straightforward in TileMill, but in Mapsforge I had to use all possible tricks for making that working.

**Comment by devemux86** [comment] 2015-05-22 19:08
I'm closing this as it's actually a limitation of our map renderer.

But I'd be happy if we could manage to hide elements behind solid geometries.

**Closed by devemux86** 2015-05-22 19:08 UTC
