### ISSUE TITLE
Add kinetic scrolling to the MapView

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#219] opened 2014-11-06 09:45 UTC
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 07, 2012 17:07:11_

Currently the map stops immediately when a move gesture is aborted. We should also support for kinetic scrolling, where the map is moved for a small time with a configurable attenuation.

This issue was originally part of issue 19 .

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=219_

**Comment by devemux86** [comment] 2015-09-23 18:49
Closed as part of #688.

**Closed by devemux86** 2015-09-23 18:49 UTC
Labels: enhancement, imported, Priority-Low

**Comment by devemux86** [comment] 2015-09-26 16:28
There is have an artifact with current fling.

We scroll (pan) the map and stop but keeping touching for 1-2", then on lift up the map moves a bit more (an additional ```onFling``` event).

That's not expected behavior, users would not consider that action sequence as fling (but as scroll), so the map should be steady at the end.

**Comment by schildbach** [comment] 2015-09-26 20:18
I cannot reproduce this on 11563db, can you maybe record a video?
