### ISSUE TITLE
Allow for free rotation of the map

### ISSUE THREAD

**Issue by mapsforge** [mapsforge/mapsforge#7] opened 2014-11-06 09:27 UTC
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on May 28, 2010 09:00:21_

Currently the MapView can only display the map according to the orientation
of the device (portrait/landscape). It should be possible to freely rotate
the map, for example based on the compass sensor.

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=7_

**Comment by Kentaree** [comment] 2015-04-16 13:51
I see there was some work done on this issue in the rotation branch, is there any further work planned on it?

**Comment by devemux86** [comment] 2015-04-16 14:04
Yes I intend also to push it more - but it's not an easy job so no promises can be made about the timing.

In the mean time you can check an external rotation implementation:
https://groups.google.com/forum/#!topic/mapsforge-dev/Zqm5IyS1jS4

**Comment by ludwigb** [comment] 2015-04-16 15:16
I kind of got stuck on this, feel free to try it out.

The problem is that the various scaling and rotation events screw up the
label positioning (e.g. try rotating the map in the Samples app and you
will see that the points do not cleanly revolve around the center).

I think also an interface is needed to retrieve label data directly from
the map file (rather than go through this strange caching via the tile
rendering). But while this is not so difficult for some map zoom levels, I
do not understand the format well enough to do this for some of the
intermediate zoom levels where data from different tiles has to be
combined.

Ludwig

**Comment by Kentaree** [comment] 2015-04-28 11:59
I've been having a look at this myself, can't say I'm noticing any big issues with label rotation. What I have noticed though is that there's some sort of touch offset in the long click event, which I'm trying to figure out at the moment. This occurs even at standard rotation, so not sure what's causing it

**Comment by ludwigb** [comment] 2016-01-12 13:17
Merged current dev with new LabelLayer from MapDataStore into rotation branch, in the Samples app the bottom example exercises map rotation. Reading the labels directly seems to work well. 
The issues are as before:
 - the positions of all touch events are all calculated wrong. Basically the lat/long position reported to the map is the non-rotated position, making all subsequent map moves wrong.
 - the visible area is not computed correctly, leading to tiles missing.
 - I have seen that the tiles are not drawn at all, just resulting in a grey area, might not be only rotation related. 
The whole rotation needs revisiting, but now that we have a working LabelLayer that is less resource hungry and draws independently of tiles, we have a much better starting position.

**Comment by devemux86** [comment] 2016-01-12 13:31
With the rewritten touch gestures, it's now easier to integrate rotation awareness to them.

**Comment by devemux86** [comment] 2019-08-01 15:39
See [VTM](https://github.com/mapsforge/vtm) OpenGL vector map library, compatible with Mapsforge maps.

**Comment by devemux86** [comment] 2024-06-04 14:44
Map rotation with Mapsforge samples and Cruiser:

<img src="https://github.com/cgeo/cgeo/assets/3484020/f512219e-362a-49d1-9ead-26edd877d845" width="50%"/><img src="https://github.com/cgeo/cgeo/assets/3484020/d36dfcb1-c8da-469c-883a-419333013f84" width="50%"/>

**Closed** 2024-06-30 07:53 UTC
Labels: enhancement, help wanted, imported

**Comment by devemux86** [comment] 2024-06-30 08:16
Rotation gesture is experimental and needs improvements.

(can be tested with the `Parameters.ROTATION_GESTURE`)

See https://github.com/mapsforge/mapsforge/issues/1495

**Comment by devemux86** [comment] 2024-06-30 08:44
[RotationMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotationMapViewer.java) demonstrates the new rotation API.
