### ISSUE TITLE
Relations with type=boundary not included

### ISSUE THREAD

**Issue by eartrumpet** [mapsforge/mapsforge#602] opened 2015-04-18 15:49 UTC
In recent OpenAndroMaps Nationalpark Berchtesgaden, http://www.openstreetmap.org/relation/4292200, is not shown. It should, because boundary=national_park and protect_class=2 are included in tag-mapping. The only difference I found to other national parks on relations is that here type=boundary is used instead of type=multipolygon (which is not so rare).
So I asked Christian if could do a tagtransform to test it, which he did:
```    <translation>
        <name>national parks to multipolygons</name>
        <description>national parks to multipolygons</description>
        <match mode="or">
            <match mode="and" type="relation">
                <tag k="boundary" v="national_park"/>
                <tag k="type"  v="boundary"/>
            </match>
            <match mode="and" type="relation">
                <tag k="boundary" v="protected_area"/>
                <tag k="type"  v="boundary"/>
            </match>
        </match>
        <output>
            <copy-all/>
            <tag k="type" v="multipolygon"/>
        </output>
    </translation>
```
Now all protected_area and national_park relations with type=boundary are shown. Seems like relations with type=boundary aren't included.

**Comment by devemux86** [comment] 2015-04-18 16:04
What map writer version and with what map reader?

Also can you post a sample of the render theme that does not work as intended?

**Comment by eartrumpet** [comment] 2015-04-18 17:27
The map was created with map writer 0.5, tested with Atlas Beta 1.2.12 and OruxMaps with MF 0.5.1
The map bayern from http://download.mapsforge.org/ has this issue for boundary=national_park too.
Just the simplest rule doesn't work for relations with type=boundary:
```
<rule e="way" k="boundary|leisure" v="protected_area|national_park|nature_reserve">
    <area fill="#00FF00" />
    <line stroke="#88FF88" stroke-width="3" />
    <caption k="name" font-style="bold" font-size="12" fill="#000000" stroke="#FFFFFF" stroke-width="2.0" />
</rule>
```

It works without issues when it's no relation:
http://www.openstreetmap.org/way/266127968
And also with relations that have type=mulitpolygon:
http://www.openstreetmap.org/relation/3354261

**Comment by eartrumpet** [comment] 2015-04-18 20:47
Just found the problem we had with inheritance of protect_class, so tag-transform works as expected now (and removed the part about it in the starting post). But the problem with type=boundary without tag-transform to type=multipolygon remains.

**Comment by devemux86** [comment] 2015-04-19 12:50
Maybe related to #586.

**Comment by eartrumpet** [comment] 2015-04-19 15:56
Thought about it too at first, but that happens when force-polygon-line=true is added in tag-mapping and in the theme one tries to fill it like an area. If you only draw a line with force-polygon-line=true, it works flawless.
In this issue, one can't draw a line at all, nor fill or show captions. So it seems to be not included at all.

**Comment by devemux86** [comment] 2015-05-13 07:37
Currently only [multipolygon](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-map-writer/src/main/java/org/mapsforge/map/writer/model/TDRelation.java#L90-L98) relations are known.

**Comment by devemux86** [comment] 2015-05-13 07:42
I'm closing this as duplicate of #245.

**Closed by devemux86** 2015-05-13 07:42 UTC
