### ISSUE TITLE
IllegalArgumentException for rectangle

### ISSUE THREAD

**Issue by jordantrain** [mapsforge/mapsforge#568] opened 2015-01-14 07:54 UTC
I have updated the Mapsforge API to current release version 0.5.0.  I received the following error report:

java.lang.IllegalArgumentException: top: 2.147483647E9, bottom: -2.147483409E9
at org.mapsforge.core.model.Rectangle.<init>(Rectangle.java:34)
at org.mapsforge.map.layer.overlay.Marker.draw(Marker.java:80)
at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:90)
at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

Unfortunately, I have no information about the circumstances that triggered the error.  That's all I have.  Any ideas?

**Comment by devemux86** [comment] 2015-01-14 08:02
Check the ```Rectangle``` constructor for the order of parameters and the conditions that must be met:
https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/model/Rectangle.java#L30-L35

**Comment by ludwigb** [comment] 2015-01-14 13:18
The origin of a rectangle is in the upper left corner, so (maybe contrary to intuition) the bottom must be larger than the top. So somewhere in your code you must be supplying the wrong arguments.

**Comment by jordantrain** [comment] 2015-01-14 21:43
Thanks, ludwigb.  It is a very rare occurrence.  Unfortunately the error report does not include traces back to my own code, so it is hard to know exactly where it is coming from and without the ability to reproduce this error I am at a loss.  C'est la vie.

**Comment by ludwigb** [comment] 2015-01-14 21:49
Well, it does come from one of your markers. It is possible that we have some sort of wrap-around situation? What zoom-level did it happen at? It is when the poles would be in view and you have a very larger marker that would wrap around the poles?

**Comment by jordantrain** [comment] 2015-01-14 21:56
Yes.  I believe it is coming from one of the markers. It looks more like an integer type number wrap-around than a pole wrap-around.  The values are at or very close to the Integer.max and Integer.min values.

**Comment by jordantrain** [comment] 2015-01-14 22:02
My own MarkerShow class extends your Marker.  I think this is the best candidate.

		  	public class MarkerShow extends Marker{
		  		MarkerHide hideableMarker;
		  		
		  		public MarkerShow(LatLong wpt, Bitmap bmp, int horizontalDisp, int verticalDisp){
		  			super(wpt,bmp,horizontalDisp,verticalDisp);
		  		}
		  		
		  		@Override
		  		public boolean onTap(LatLong tapLatLong, Point viewPosition, Point tapPoint){
		  			//Toast.makeText(context, "Pin Tapped", Toast.LENGTH_LONG).show();
		  			Layers layers = mapView.getLayerManager().getLayers();
		  			if(hideableMarker != null && this.contains(viewPosition, tapPoint) && !layers.contains(hideableMarker)){
		  				layers.add(hideableMarker);
		  				mapView.getLayerManager().redrawLayers();
		  			}
		  			return false;
		  		}
		  		
		  		public void add(MarkerHide hideable){
		  			hideableMarker = hideable;
		  		}
		  		
		  	}

**Comment by ludwigb** [comment] 2015-01-14 22:07
Any idea what zoom level it happened at? The values kind of suggest that you are at a very low zoom level, so the marker spans a lot of points (which are then mapped back onto the screen space). Also what lat/long values?

**Comment by jordantrain** [comment] 2015-01-14 22:13
ludwigb, 
Unfortunately, I don't have the user's conditions.  I've tried dropping markers around the poles, the equator and the Prime Meridian.  No luck in reproducing this.  It may be that the user was somehow able to sneak in an illegal coordinate value for a waypoint but I don't see how that would relate to the onTap function which looks to be the best bet so far.

**Comment by jordantrain** [comment] 2015-01-14 22:16
The documentation states that the viewPosition Point variable in the onTap function is the xy position of the layer if available.  Is this the upper left coordinate or some other point within the layer?

**Comment by ludwigb** [comment] 2015-01-14 22:18
There is funny stuff that can happen with Mercator Projection when you get towards the poles (where it cannot be applied). What are the restrictions that you apply to user coordinates? Or could it be a locale problem (e.g. , instead of . as decimal point) ?

**Comment by jordantrain** [comment] 2015-01-14 22:20
I identified an issue where the user could enter a value like a latitude of -90 degrees, 1 minute which would translate to -90 - 1/60 degrees which is an illegal value. We will be correcting this in the next update.

**Comment by ludwigb** [comment] 2015-01-14 22:25
There is a 
LATITUDE_MAX = 85.05112877980659
defined in MercatorProjection, there is some mathematical reason for this, after that values get funny.

**Comment by jordantrain** [comment] 2015-01-14 22:26
OK.  Thanks for your time and expertise.  We will use that value.  How about the LATITUDE_MIN?

**Comment by jordantrain** [comment] 2015-01-14 22:28
GOT IT.   LOOKS LIKE  -85.05112877980659

**Comment by ludwigb** [comment] 2015-01-14 22:28
Same, it is just the same calculation on the other side. Plus you will need to make sure that you do not cross the line with the size of your marker. Best to use the constants, rather than the numbers.

**Comment by devemux86** [comment] 2015-01-15 07:38
I read now the whole conversation.
It's an unfortunate situation for an app and I'm glad there is a solution to all this.

For the record here is [MercatorProjection](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/MercatorProjection.java#L39-L47) bounds.

**Comment by ludwigb** [comment] 2015-01-15 07:49
If that is the solution, that is. 
But, yes, what first seemed like a simple confusion of arguments, turns out to be a bit more complex: that certain values for markers can trigger exceptions much later that crash the entire app. The question is how should be handle this: I am neither in favour of just doing a catch-all around the marker drawing (that  invites sloppiness and unpredictable behaviour when certain markers just disappear) nor is crashing the right way. Maybe we should have this discussion on the mailing list.

**Comment by devemux86** [comment] 2015-01-15 07:54
Maybe I misunderstood, but I got the impression that in @jordantrain 's app the user can enter by hand the coordinates.
And now a check for the entered values is included.

**Comment by ludwigb** [comment] 2015-01-15 08:21
The problem is that we have no way of verifying this: when I looked at the values I thought it was maybe some sort of wrap-around: a marker very close to the allowed borders that takes up more virtual space (in map-pixel coordinates, not screen-pixel coordinates) so that it wraps around and then triggers an invalid rectangle construction. Thilo would say: more unit tests. But maybe for the moment we can close this issue again.

**Closed by ludwigb** 2015-01-15 08:21 UTC
