### ISSUE TITLE
rotate map

### ISSUE THREAD

**Issue by farhad-kargaran** [mapsforge/mapsforge#981] opened 2017-07-31 04:47 UTC
Hi, I think it would be great if user could rotate map by two finger like google map.

**Comment by devemux86** [comment] 2017-07-31 06:42
Mapsforge is a vector map library, so proper map rotation must maintain labels / symbols orientation.
Raster maps are different, can rotate easily since they're simple pre-generated bitmaps.
Also Mapsforge uses (hardware accelerated) software rendering, and all rotated elements calculations could not very CPU friendly.

We have https://github.com/mapsforge/mapsforge/tree/rotation branch where some work for map rotation was done, but was not finished.

And there is [RotateMapViewer](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-samples-android/src/main/java/org/mapsforge/samples/android/RotateMapViewer.java) in Samples, demonstrating a rotation of the whole map view.

But you can check [VTM](https://github.com/mapsforge/vtm), which is an OpenGL vector map library compatible with Mapsforge maps, having map rotation and many more features.

Closing as duplicate of #7.

**Closed by devemux86** 2017-07-31 06:42 UTC
Labels: duplicate

**Comment by farhad-kargaran** [comment] 2017-07-31 06:48
Thank you very much for your answer
