### ISSUE TITLE
Real problem displaying several maps

### ISSUE THREAD

**Issue by 2ndGAB** [mapsforge/mapsforge#769] opened 2016-01-11 17:58 UTC
Hello,

I've tested your Samples application because I experienced an issue in my application using OSMDroid and MapsForgeForOSMDroid module where it was impossible to display several maps together because of a white background around maps region which cover the map beside.

And the problem is also present in your Samples application.
I propose you to download auvergne.map and rhone-alpes.map from france directory, renaming these files germany.map and second.map and you will get the result shown [here](http://i.imgur.com/E2qso89.png)

Regards,

**Comment by devemux86** [comment] 2016-01-11 18:04
We now have `sea` and `nosea` declarations in [themes](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml#L144-L150) that prevent those maps from turn completely transparent their backgrounds.

(Duplicate of #579)

**Comment by 2ndGAB** [comment] 2016-01-11 18:14
Hi devemux86,
That's a good news but could you explain a bit more precisely what to change in Samples application to get it working as expected please?

**Comment by devemux86** [comment] 2016-01-11 18:22
In the render theme try removing the [map-background-outside](https://github.com/mapsforge/mapsforge/blob/master/Applications/Android/Samples/assets/renderthemes/rendertheme-v4.xml#L4) and see what happens.

**Comment by devemux86** [comment] 2016-01-11 18:23
You may need to comment also the rules mentioned above.

**Comment by 2ndGAB** [comment] 2016-01-11 18:35
Ok, that works with the modifications mentionned.

But it seems it should be better to use [MultiMapDataStore](https://github.com/mapsforge/mapsforge/blob/6e2cd3fc79cb8343481e78f89311d0ad02464385/docs/MapDataStore.md#multimapdatastore)

Thanks

**Comment by devemux86** [comment] 2016-01-11 18:39
Which suggestion of the above you used?

`MultiMapDataStore` is the recommended solution as it uses far less resources.

**Comment by 2ndGAB** [comment] 2016-01-11 18:52
I currently modified the theme.

**Closed** 2016-01-11 19:19 UTC
