### ISSUE TITLE
RenderTheme NPE

### ISSUE THREAD

**Issue by emdete** [mapsforge/mapsforge#652] opened 2015-07-21 20:55 UTC
error e=java.lang.NullPointerException: Attempt to write to field 'java.util.LinkedHashMap$LinkedEntry java.util.LinkedHashMap$LinkedEntry.nxt' on a nullobject reference
java.lang.NullPointerException: Attempt to write to field 'java.util.LinkedHashMap$LinkedEntry java.util.LinkedHashMap$LinkedEntry.nxt' on a null objectreference
    at java.util.LinkedHashMap.makeTail(LinkedHashMap.java:271)
    at java.util.LinkedHashMap.get(LinkedHashMap.java:257)
    at org.mapsforge.map.rendertheme.rule.RenderTheme.matchWay(RenderTheme.java:207)
    at org.mapsforge.map.rendertheme.rule.RenderTheme.matchLinearWay(RenderTheme.java:125)
    at org.mapsforge.map.layer.renderer.DatabaseRenderer.renderWay(DatabaseRenderer.java:443)
    at org.mapsforge.map.layer.renderer.DatabaseRenderer.processReadMapData(DatabaseRenderer.java:417)
    at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:184)
    at org.mapsforge.map.layer.renderer.MapWorker.renderTile(MapWorker.java:88)
    at org.mapsforge.map.layer.renderer.MapWorker.doWork(MapWorker.java:65)
    at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)

mapsforge version 0.5.1, maps from openandromaps, theme andromaps_light.

**Comment by ludwigb** [comment] 2015-10-10 09:35
Duplicate of #567

**Closed by ludwigb** 2015-10-10 09:35 UTC
Labels: bug, duplicate
