### ISSUE TITLE
Peculiar behavior of new label layer

### ISSUE THREAD

**Issue by Klaus-Tockloth** [mapsforge/mapsforge#776] opened 2016-01-31 07:50 UTC
The new label layer shows a peculiar behavior ...

That's the result **with** the label layer (only a few house numbers):

![bildschirmfoto 2016-01-30 um 22 18 27](https://cloud.githubusercontent.com/assets/5493128/12700929/d6787a4a-c7f6-11e5-86f5-75dc676e4f29.jpg)

And this is the result **without** the label layer (nearly all (but not all) house numbers are visible):

![bildschirmfoto 2016-01-30 um 22 19 07](https://cloud.githubusercontent.com/assets/5493128/12700926/b22545f6-c7f6-11e5-9d34-8358e88f95a9.jpg)

And this is the situation in OSM:
http://www.openstreetmap.org/#map=19/51.96395/7.63848

![bildschirmfoto 2016-01-31 um 08 48 47](https://cloud.githubusercontent.com/assets/5493128/12700946/8fce48f8-c7f7-11e5-9f55-09e6f6423c8a.jpg)

The problem occurs with Cruiser (1.4.0 - 20160130) and with Atlas (1.2.0-20160130).

Klaus

**Comment by devemux86** [comment] 2016-01-31 10:07
I can confirm the issue - it can also be reproduced with Samples.

Old `LabelLayer`:
![old](https://cloud.githubusercontent.com/assets/3484020/12701477/17c5231a-c813-11e5-8601-a63f145f6ed8.png)

New `LabelLayer`:
![new](https://cloud.githubusercontent.com/assets/3484020/12701479/1ef4f142-c813-11e5-86f2-c07cd38cecf9.png)

(related to #763)

**Comment by ludwigb** [comment] 2016-01-31 11:22
I think the reason is the following:

as an optimization we (= I, culpa mea) only store ways if they have a name
to them (otherwise we would essentially need to cache all data). The houses
here have probably no name, but a house number.
The house numbers that do show up are probably points (not on ways, thats
is why they are on entrances and the like).

The fix will be to also store ways if they have a house number, or an
elevation ....

Ludwig

**Comment by applantation** [comment] 2016-01-31 11:59
I just pushed a fix to dev.

**Comment by devemux86** [comment] 2016-01-31 12:26
That did the job.

It's worth mentioning that we support:
- In nodes: name, addr:housenumber, ele
- In ways: name, addr:housenumber, ref

**Comment by ludwigb** [comment] 2016-01-31 12:33
Yes, nodes are always included, ways now only if they have additional
information that is displayed as a label.

**Comment by eartrumpet** [comment] 2016-02-07 18:05
> Yes, nodes are always included, ways now only if they have additional information that is displayed as a label.

I don't know the reason for that, but it creates unexpected behavior. 

For example for amenity=parking, it's often used as ways without any of the other information. But I want to display the symbol for parking (as in renderthemeV4) and that works well without label layer, but not with label layer activated.

**Comment by devemux86** [comment] 2016-02-07 18:34
@eartrumpet you mean the new label layer?

**Comment by devemux86** [comment] 2016-02-07 19:10
The comparison can be done in the two Samples examples:
- the old "Separate LabelLayer using LabelStore"
- the new "Threaded LabelLayer using MapDataStore"

New implementation at same area / zoom level shows far less area symbols e.g. parkings.

**Comment by Klaus-Tockloth** [comment] 2016-02-07 19:29
Question: What triggers a street label to go into the label layer?

I general have the problem that not all street labels are shown on the map. Screenshot from Atlas:

![bildschirmfoto 2016-02-07 um 20 18 09](https://cloud.githubusercontent.com/assets/5493128/12874703/31981204-cdd9-11e5-846f-02a19a208b10.jpg)

What you see on the screenshot is only the street label "Hafenweg" (a residential), but not the labels of the streets in the north (also residentials). The label layer is activated. I have made tests with Atlas 1.2.1 and Cruiser 1.4.1. No results is convincing. Maybe I'm doing something wrong. Any ideas?

Klaus

**Comment by devemux86** [comment] 2016-02-07 19:38
I agree that it's not the desired behavior for road labels (with label layer or not).
See also #644 for relevant discussion.

**Comment by eartrumpet** [comment] 2016-02-07 19:47
Yes, the new label layer. Tested with latest Atlas/Cruiser from today.
Symbols for ways are not shown independent of zoom level if the way has no name/addr:housenumber/ref.
That makes sense if the label layer contains only captions, but not for symbols where those values are irrelevant.

**Comment by devemux86** [comment] 2016-02-07 19:51
Yes I can confirm that, I'm reopening the issue.

**Comment by devemux86** [comment] 2016-02-07 20:02
Thank you both for the quick feedback.
Before making any code changes, let's wait for @ludwigb 's answer who played with that part.

**Comment by devemux86** [comment] 2016-02-07 21:02
Essentially what happens here with the new implementation is that we opted to render only ways that have a [label](https://github.com/mapsforge/mapsforge/blob/dev/mapsforge-map-reader/src/main/java/org/mapsforge/map/reader/MapFile.java#L821).
The selector is not `ALL` in case of `LabelLayer`, it's `LABELS`.

**Comment by eartrumpet** [comment] 2016-02-07 21:32
That's what I meant when I wrote those values are irrelevant if symbols are moved to the label layer. It makes sense to move captions only in the label layer and leave the selector `LABELS` as it is, or move captions and symbols (as it is the case now) and use the selector `ALL`.

**Comment by ludwigb** [comment] 2016-02-08 00:08
The analysis is correct, the question is how we solve this problem without
bringing all road data into the layer (which we do not want as that would
most likely cause OOMs, just too much data for all the tiles together).

Those labels should not be on the tile layer either, a main motivation for
the LabelLayer is support rotation, so everything that needs rotation
should go onto the LabelLayer.

So, either we can find a good way to customize what we consider a Label
(so, e.g. a method on the LabelLayer isLabel() that can be overwritten in
user code, which could be expensive as it needs testing for every condition
in it for every way) or alternatively suggest some preprocessing for maps,
e.g. with area2points to transform such ways into additional poi info in
the map file (I think this would we the preferred way for those who are
making their own maps).

Thoughts?

Ludwig

**Comment by eartrumpet** [comment] 2016-02-08 07:04
Now I understand.
Could the rendertheme be used? At loading the theme with activated label layer, check for every symbol instruction and find the defining rule (which hasn't any `*`). That would be best for compatibility, but may be expensive at theme loading time.

**Comment by devemux86** [comment] 2016-02-08 07:36
I'd avoid putting (more) work in render theme processing.
Despite our improved parsing, I still find several occasions where themes are heavy and as consequence the engine seems slow to users.
I'd prefer any method that pulls the weight away from the clients.
Note: Label layer 'as is' is already cpu intensive compared to regular rendering.

**Comment by eartrumpet** [comment] 2016-02-08 10:04
I'm aware of that, but it's still the choice of the user to use a more complex theme.
Every other solution which relies on preprocessed maps etc. has probably issues with compatibility. One of the strengths of mapsforge is that every user can adapt a theme (or create a new one), and lesser preprocessing helps this. If only symbols of certain tags that are predefined appear in the label layer, it won't work if the map creator had different items in mind than a user. And it breaks consistency: it would work without label layer, but not with.

**Comment by ludwigb** [comment] 2016-02-10 09:00
I have just added a hook into the MapDatabase that allows defining a method that will select additional ways into the LabelLayer depending on tags. By default, only the ways that were previously included selected, but the method allows inspecting the tags. 

The motivation is as follows:
-- for memory reasons we should include as few ways into the LabelLayer.
-- additional freedom for those who design apps that allow user defined render themes. 
-- apps that do not allow user maps/renderthemes should not be affected in a significant way. 

Be aware that the new method can be expensive as every way has to be inspected. If an app decides to include every way (by returning true regardless of tags), the app might be experiencing OOM errors. 

I think this solution gives most of the freedom desired but without too much of an overhead.

**Comment by devemux86** [comment] 2016-02-10 09:08
Thanks @ludwigb, I will test its performance.

**Comment by devemux86** [comment] 2016-02-11 14:16
_I published new Atlas / Cruiser with the above hook including all ways in `LabelLayer`._

Let's see in action if there are any problems - leaving the issue open for now.
I'm in favor of any performance boost, though users expect to see the same elements in both layer methods, so we'll have more questions like this.

**Comment by Klaus-Tockloth** [comment] 2016-02-11 17:20
How to test this new feature? What are the use cases?

**Comment by devemux86** [comment] 2016-02-11 17:29
It's about what @eartrumpet mentioned above.
Ways that have not label (but we want to show a symbol on them), are not included by default in new `LabelLay. e.g. parkings with RenderThemeV4.

@ludwigb posted a hook above (which I included), permitting to have old behavior back, i.e. parse all ways regardless of their labeling.

**Comment by devemux86** [comment] 2016-02-11 17:36
@Klaus-Tockloth see also my above [post](https://github.com/mapsforge/mapsforge/issues/776#issuecomment-181086995) for Samples.

**Comment by eartrumpet** [comment] 2016-02-12 10:31
> I published new Atlas / Cruiser with the above hook including all ways in LabelLayer.
Thanks @devemux86 

I just did a quick test, now everything works again as expected (label layer show more labels again because of tile border issue without label layer). 

Of course it's slower than without label layer, the interesting difference would be comparing this with the other method (without all ways included).

**Comment by devemux86** [comment] 2016-02-12 10:39
> the interesting difference would be comparing this with the other method (without all ways included)

The Samples example "Threaded LabelLayer using MapDataStore" includes only the labelled ways.

**Comment by eartrumpet** [comment] 2016-02-13 18:33
I tested all three variants in current Samples apk (separate labellayer using mapdatastore, threaded labellayer using mapdatastore, separate labellayer using labelstore), same map, same theme (renderthemeV4 topo with all overlays), same position. Taking the rendertime showed no significant differences between all three implementations, I tested at low and high zoom.

**Comment by devemux86** [comment] 2016-02-13 18:40
Are you sure?

Regular "Map Viewer Rendertheme V4" and old "Separate LabelLayer using LabelStore" show all parkings.

New "Threaded LabelLayer using MapDataStore" shows only labeled ways, so far less parkings.
("Separate LabelLayer using MapDataStore" is the same without threading)

**Comment by eartrumpet** [comment] 2016-02-13 18:42
Of course more parkings are shown with labelstore in comparison to mapdatastore, but no difference in rendertime (1st gen. Moto G LTE).

**Closed** 2016-02-19 13:38 UTC
Labels: bug
