### ISSUE TITLE
blank tiles with Multithreaded Rendering

### ISSUE THREAD

**Issue by calimoto-GmbH** [mapsforge/mapsforge#806] opened 2016-03-21 14:08 UTC
if multithread rendering is enabled a lot of blank tiles randomly appear:

![2016-03-21 13 53 38](https://cloud.githubusercontent.com/assets/9555809/13920771/048e143a-ef75-11e5-93c0-39f396b4c05a.png)
![2016-03-21 13 53 23](https://cloud.githubusercontent.com/assets/9555809/13920773/06e4e92a-ef75-11e5-9c33-6bd5a122a9e4.png)

and a lot of warnings in the mapfiles are logged:

invalid number of way coordinate blocks: 0
invalid way tag ID: 10496

to prove just use the samples app and increase the render Threads in the settings.

**Comment by devemux86** [comment] 2016-03-21 14:14
Multi-threading rendering is normally not recommended (default is 1 thread), as there are [issues](https://github.com/mapsforge/mapsforge/issues/591).

Did you try with the default (in Samples) persistent cache enabled?
Because there is an [issue](https://github.com/mapsforge/mapsforge/issues/764) about missing tiles with that.

**Comment by SebastianDa** [comment] 2016-03-21 14:40
yes both persistent cache (enabled and disabled) behave the same.

**Comment by devemux86** [comment] 2016-03-28 10:43
Closing in favor of #591.

**Comment by bvgastel** [comment] 2016-08-12 11:43
Actually the blank titles appears to be due to race conditions in MapFile. Multiple render threads are reading data from a ```readBuffer``` attribute in MapFile that is set differently by each thread, therefore the threads interfere with each other. I can contribute a fix for this if requested (have it working).

**Comment by devemux86** [comment] 2016-08-12 11:47
@bvgastel if you have something working all will be benefit from an PR!

**Comment by bvgastel** [comment] 2016-08-12 12:11
I have made a PR. Hope it helps! If you need more information, please let me know.

**Comment by devemux86** [comment] 2016-08-13 14:23
Also note that the black tiles usually appear with large number of threads.

**Comment by bvgastel** [comment] 2016-08-13 16:19
Black or blank?

**Comment by devemux86** [comment] 2016-08-13 16:20
Sorry blank (I corrected it).

**Comment by bvgastel** [comment] 2016-08-13 16:22
:)

It can take a while to fill in the blank tiles, but the blank tiles are eventually painted in with map data (as opposed to the old behaviour that the blank tiles are not replaced).

**Comment by devemux86** [comment] 2016-08-19 17:51
@calimoto-GmbH could you check the latest master?

**Comment by devemux86** [comment] 2016-09-03 12:31
Closing here, if there any issues please report.

**Closed by devemux86** 2016-09-03 12:31 UTC
Labels: bug

**Comment by DrMarkEy** [comment] 2016-12-04 09:54
I also encounter blank tiles when I enable multithreaded rendering. It happens more often if I keep the CPU  busy through some other operations I perform in background while displaying the map. Also the more threads I allow mapsforge to use, the more often blank tiles appear. 

Here is a picture of such a blank tile:
![mapsforge-error](https://cloud.githubusercontent.com/assets/21967688/20865330/0c8f7dd0-ba0f-11e6-8cb3-760ae0a31cf9.png)

Sometimes there may also be partially blank tiles, like this one:
![mapsforge-error2](https://cloud.githubusercontent.com/assets/21967688/20865350/78c4d09a-ba0f-11e6-86c5-abb71c44e96f.png)

 I kind of narrowed it down to the following: Somehow broken (empty) tiles are generated(?) and saved in the FileSystemTileCache.  When trying to load those tiles I get the following error Chain:

 E/FileSystemTileCache: /storage/emulated/0/Android/data/<packagename>/cache/mapTilecache/13/4293/2790.tile: open failed: ENOENT (No such file or directory)
java.io.FileNotFoundException: /storage/emulated/0/Android/data/<packagename>/cache/mapTilecache/13/4293/2790.tile: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at org.mapsforge.map.layer.cache.FileSystemTileCache.get(FileSystemTileCache.java:253)
	at org.mapsforge.map.layer.cache.TwoLevelTileCache.setWorkingSet(TwoLevelTileCache.java:101)
	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:88)
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:94)
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140)
 Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	at java.io.FileInputStream.<init>(FileInputStream.java:76) 
	at org.mapsforge.map.layer.cache.FileSystemTileCache.get(FileSystemTileCache.java:253) 
	at org.mapsforge.map.layer.cache.TwoLevelTileCache.setWorkingSet(TwoLevelTileCache.java:101) 
	at org.mapsforge.map.layer.TileLayer.draw(TileLayer.java:88) 
	at org.mapsforge.map.layer.LayerManager.doWork(LayerManager.java:94) 
	at org.mapsforge.map.util.PausableThread.run(PausableThread.java:140) 

Which is captured by the catch clause in FileSystemTileCache.java: 264. For reasons I don't know, the tile is not recreated by the remove(key) statement that follows and therefore stays blank.

I also found the following error:

java.lang.ArrayIndexOutOfBoundsException: length=29645; index=29645
   at org.mapsforge.map.reader.ReadBuffer.readSignedInt(ReadBuffer.java:145)
   at org.mapsforge.map.reader.MapFile.decodeWayNodesSingleDelta(MapFile.java:352)
   at org.mapsforge.map.reader.MapFile.processWayDataBlock(MapFile.java:681)
   at org.mapsforge.map.reader.MapFile.processWays(MapFile.java:782)
   at org.mapsforge.map.reader.MapFile.processBlock(MapFile.java:451)
   at org.mapsforge.map.reader.MapFile.processBlocks(MapFile.java:559)
   at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:854)
   at org.mapsforge.map.reader.MapFile.readMapData(MapFile.java:829)
   at org.mapsforge.map.datastore.MultiMapDataStore.readMapData(MultiMapDataStore.java:148)
   at org.mapsforge.map.datastore.MultiMapDataStore.readMapData(MultiMapDataStore.java:137)
   at org.mapsforge.map.layer.renderer.DatabaseRenderer.executeJob(DatabaseRenderer.java:90)
   at org.mapsforge.map.layer.renderer.MapWorkerPool$MapWorker.run(MapWorkerPool.java:155)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)

Which may or may not be related to the creation of the broken tile in the first place. Although I'm not deep enough into the tile creation code to investigate this.




I'm using Android and a Samsung Galaxy S5 Mini for Testing.

**Comment by devemux86** [comment] 2016-12-04 10:04
- Which Mapsforge version are you using?
- How many threads?

Above multi-threaded fix is included in latest `master-SNAPSHOT`.

**Comment by DrMarkEy** [comment] 2016-12-04 11:14
I use version 0.6.1 with 2 threads.

**Comment by devemux86** [comment] 2016-12-04 13:17
Multi-threading is not working correctly with release `0.6.1`.
If you want to use it, you need to advance to `master-SNAPSHOT` (see instructions in [integration guide](https://github.com/mapsforge/mapsforge/blob/master/docs/Integration.md)).

**Comment by DrMarkEy** [comment] 2016-12-04 13:52
Migrating to master-SNAPSHOT solved it for me. Thank you very much!
