### ISSUE TITLE
Tag mapping osm-tag value is not designed for numerical values

### ISSUE THREAD

**Issue by andreynovikov** [mapsforge/mapsforge#822] opened 2016-04-12 13:21 UTC
I want to add some numerical tags to my map file, like height and building:levels. But osm-tag value attribute is required and accepts only single value. It would be nice to be able to write `value="*"` or even better make value attribute optional.

**Comment by devemux86** [comment] 2016-04-12 13:28
Old (and popular) request that could make our map creation much easier!
Closing as duplicate of #257.

**Closed by devemux86** 2016-04-12 13:28 UTC
Labels: duplicate
